/**
 * Export Document Tool - 대화 및 문서 내보내기
 * 대화, 회의록, 프로젝트 자료를 PDF/Markdown/HTML로 내보내는 기능
 */

import { logger } from '../../utils/logger.js';
import Database from 'better-sqlite3';
import fs from 'fs';
import path from 'path';

/**
 * 문서 내보내기 도구 생성
 * @param {Object} options - 설정 옵션
 * @returns {Array<Object>} MCP Tool 객체 배열
 */
export function createExportDocumentTools(options = {}) {
  const {
    dbPath = './athena-data/athena.db',
    workspaceRoot = process.cwd(),
    outputDir = 'exports'
  } = options;

  const db = new Database(dbPath);

  // 내보내기 디렉토리 생성
  const fullOutputDir = path.join(workspaceRoot, outputDir);
  if (!fs.existsSync(fullOutputDir)) {
    fs.mkdirSync(fullOutputDir, { recursive: true });
  }

  // 마크다운을 HTML로 변환 (간단한 변환)
  const markdownToHtml = (markdown) => {
    return markdown
      // 헤더
      .replace(/^### (.*$)/gim, '<h3>$1</h3>')
      .replace(/^## (.*$)/gim, '<h2>$1</h2>')
      .replace(/^# (.*$)/gim, '<h1>$1</h1>')
      // 굵게/기울임
      .replace(/\*\*\*(.*?)\*\*\*/gim, '<strong><em>$1</em></strong>')
      .replace(/\*\*(.*?)\*\*/gim, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/gim, '<em>$1</em>')
      // 코드 블록
      .replace(/```(\w+)?\n([\s\S]*?)```/gim, '<pre><code class="language-$1">$2</code></pre>')
      .replace(/`(.*?)`/gim, '<code>$1</code>')
      // 링크
      .replace(/\[([^\]]+)\]\(([^)]+)\)/gim, '<a href="$2">$1</a>')
      // 리스트
      .replace(/^\s*[-*]\s+(.*)$/gim, '<li>$1</li>')
      .replace(/(<li>.*<\/li>)/s, '<ul>$1</ul>')
      .replace(/^\s*\d+\.\s+(.*)$/gim, '<li>$1</li>')
      // 줄바꿈
      .replace(/\n\n/g, '</p><p>')
      .replace(/\n/g, '<br>');
  };

  // HTML 문서 템플릿
  const createHtmlDocument = (title, content, options = {}) => {
    const { author = 'Athena AI', date = new Date().toLocaleDateString('ko-KR'), theme = 'light' } = options;

    const themeStyles = theme === 'dark' ? `
      body { background: #1a1a2e; color: #eee; }
      h1, h2, h3 { color: #00d9ff; }
      pre { background: #16213e; }
      .message.user { background: #0f3460; }
      .message.assistant { background: #1a1a2e; border: 1px solid #333; }
    ` : `
      body { background: #fff; color: #333; }
      h1, h2, h3 { color: #2c3e50; }
      pre { background: #f4f4f4; }
      .message.user { background: #e3f2fd; }
      .message.assistant { background: #f5f5f5; }
    `;

    return `<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6; padding: 2rem; max-width: 900px; margin: 0 auto;
    }
    ${themeStyles}
    h1 { margin-bottom: 0.5rem; }
    .meta { color: #888; margin-bottom: 2rem; font-size: 0.9rem; }
    .message { padding: 1rem; border-radius: 8px; margin-bottom: 1rem; }
    .message .role { font-weight: bold; margin-bottom: 0.5rem; }
    .message .time { font-size: 0.8rem; color: #888; }
    pre { padding: 1rem; border-radius: 4px; overflow-x: auto; margin: 1rem 0; }
    code { font-family: 'Fira Code', monospace; font-size: 0.9em; }
    ul, ol { margin-left: 1.5rem; margin-bottom: 1rem; }
    p { margin-bottom: 1rem; }
    .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #ddd; font-size: 0.8rem; color: #888; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div class="meta">
    <span>작성자: ${author}</span> |
    <span>날짜: ${date}</span>
  </div>
  <div class="content">
    ${content}
  </div>
  <div class="footer">
    Generated by Athena AI • ${new Date().toLocaleString('ko-KR')}
  </div>
</body>
</html>`;
  };

  return [
    // 세션 대화 내보내기
    {
      name: 'export_conversation',
      description: '채팅 세션의 대화 내용을 파일로 내보냅니다.',
      inputSchema: {
        type: 'object',
        properties: {
          sessionId: {
            type: 'string',
            description: '내보낼 세션 ID'
          },
          format: {
            type: 'string',
            enum: ['markdown', 'html', 'json', 'txt'],
            description: '출력 형식',
            default: 'markdown'
          },
          title: {
            type: 'string',
            description: '문서 제목 (기본: 세션 제목)'
          },
          includeMetadata: {
            type: 'boolean',
            description: '메타데이터 포함 여부',
            default: true
          },
          theme: {
            type: 'string',
            enum: ['light', 'dark'],
            description: 'HTML 테마',
            default: 'light'
          }
        },
        required: ['sessionId']
      },
      execute: async (args) => {
        const {
          sessionId,
          format = 'markdown',
          title,
          includeMetadata = true,
          theme = 'light'
        } = args;

        try {
          // 세션 정보 조회
          const session = db.prepare('SELECT * FROM sessions WHERE id = ?').get(sessionId);
          if (!session) {
            throw new Error('세션을 찾을 수 없습니다');
          }

          // 메시지 조회
          const messages = db.prepare(`
            SELECT * FROM short_term_memory
            WHERE session_id = ?
            ORDER BY created_at ASC
          `).all(sessionId);

          if (messages.length === 0) {
            throw new Error('내보낼 메시지가 없습니다');
          }

          const docTitle = title || session.title || `대화 기록 - ${sessionId}`;
          let content = '';
          let outputPath = '';
          const timestamp = Date.now();

          switch (format) {
            case 'markdown':
              content = `# ${docTitle}\n\n`;
              if (includeMetadata) {
                content += `> 세션 ID: ${sessionId}\n`;
                content += `> 생성일: ${session.created_at}\n\n`;
                content += `---\n\n`;
              }

              messages.forEach(msg => {
                const role = msg.message_type === 'user' ? '👤 사용자' : '🤖 Athena';
                const time = new Date(msg.created_at).toLocaleTimeString('ko-KR');
                content += `### ${role} (${time})\n\n`;
                content += `${msg.content}\n\n`;
              });

              outputPath = path.join(fullOutputDir, `conversation_${timestamp}.md`);
              break;

            case 'html':
              let htmlContent = '';
              messages.forEach(msg => {
                const role = msg.message_type === 'user' ? 'user' : 'assistant';
                const roleName = role === 'user' ? '👤 사용자' : '🤖 Athena';
                const time = new Date(msg.created_at).toLocaleTimeString('ko-KR');
                const contentHtml = markdownToHtml(msg.content);

                htmlContent += `<div class="message ${role}">
                  <div class="role">${roleName} <span class="time">${time}</span></div>
                  <div class="body"><p>${contentHtml}</p></div>
                </div>\n`;
              });

              content = createHtmlDocument(docTitle, htmlContent, { theme });
              outputPath = path.join(fullOutputDir, `conversation_${timestamp}.html`);
              break;

            case 'json':
              content = JSON.stringify({
                title: docTitle,
                sessionId,
                createdAt: session.created_at,
                exportedAt: new Date().toISOString(),
                messages: messages.map(m => ({
                  role: m.message_type,
                  content: m.content,
                  timestamp: m.created_at,
                  metadata: m.metadata ? JSON.parse(m.metadata) : null
                }))
              }, null, 2);
              outputPath = path.join(fullOutputDir, `conversation_${timestamp}.json`);
              break;

            case 'txt':
              content = `${docTitle}\n${'='.repeat(docTitle.length)}\n\n`;
              messages.forEach(msg => {
                const role = msg.message_type === 'user' ? '[사용자]' : '[Athena]';
                const time = new Date(msg.created_at).toLocaleTimeString('ko-KR');
                content += `${role} (${time})\n`;
                content += `${msg.content}\n\n`;
                content += `-`.repeat(50) + '\n\n';
              });
              outputPath = path.join(fullOutputDir, `conversation_${timestamp}.txt`);
              break;
          }

          fs.writeFileSync(outputPath, content, 'utf-8');

          logger.info('대화 내보내기 완료', { sessionId, format, outputPath });

          return {
            success: true,
            filePath: path.relative(workspaceRoot, outputPath),
            absolutePath: outputPath,
            format,
            messagesCount: messages.length,
            fileSize: fs.statSync(outputPath).size
          };

        } catch (error) {
          logger.error('대화 내보내기 오류', error);
          throw new Error(`내보내기 실패: ${error.message}`);
        }
      }
    },

    // 회의록 내보내기
    {
      name: 'export_meeting_minutes',
      description: '회의록 형식으로 대화를 정리하여 내보냅니다.',
      inputSchema: {
        type: 'object',
        properties: {
          sessionId: {
            type: 'string',
            description: '세션 ID'
          },
          meetingInfo: {
            type: 'object',
            description: '회의 정보',
            properties: {
              title: { type: 'string', description: '회의 제목' },
              date: { type: 'string', description: '회의 일시' },
              participants: { type: 'array', items: { type: 'string' }, description: '참석자' },
              location: { type: 'string', description: '장소' }
            }
          },
          format: {
            type: 'string',
            enum: ['markdown', 'html'],
            default: 'markdown'
          }
        },
        required: ['sessionId']
      },
      execute: async (args) => {
        const { sessionId, meetingInfo = {}, format = 'markdown' } = args;

        try {
          const session = db.prepare('SELECT * FROM sessions WHERE id = ?').get(sessionId);
          const messages = db.prepare(`
            SELECT * FROM short_term_memory
            WHERE session_id = ?
            ORDER BY created_at ASC
          `).all(sessionId);

          const title = meetingInfo.title || session?.title || '회의록';
          const date = meetingInfo.date || new Date().toLocaleDateString('ko-KR');
          const participants = meetingInfo.participants || ['참석자 정보 없음'];
          const location = meetingInfo.location || '온라인';

          let content = '';

          if (format === 'markdown') {
            content = `# 📋 ${title}\n\n`;
            content += `## 회의 정보\n\n`;
            content += `| 항목 | 내용 |\n`;
            content += `|------|------|\n`;
            content += `| 일시 | ${date} |\n`;
            content += `| 장소 | ${location} |\n`;
            content += `| 참석자 | ${participants.join(', ')} |\n\n`;
            content += `---\n\n`;
            content += `## 회의 내용\n\n`;

            messages.forEach((msg, index) => {
              if (msg.message_type === 'assistant') {
                content += `### ${index + 1}. AI 분석\n\n`;
                content += `${msg.content}\n\n`;
              } else {
                content += `**질문/요청:** ${msg.content}\n\n`;
              }
            });

            content += `---\n\n`;
            content += `*이 회의록은 Athena AI에 의해 자동 생성되었습니다.*\n`;
            content += `*생성 시간: ${new Date().toLocaleString('ko-KR')}*\n`;
          } else {
            let htmlContent = `
              <table class="meeting-info" style="width:100%;border-collapse:collapse;margin-bottom:2rem;">
                <tr><th style="text-align:left;padding:0.5rem;border:1px solid #ddd;background:#f5f5f5;">일시</th><td style="padding:0.5rem;border:1px solid #ddd;">${date}</td></tr>
                <tr><th style="text-align:left;padding:0.5rem;border:1px solid #ddd;background:#f5f5f5;">장소</th><td style="padding:0.5rem;border:1px solid #ddd;">${location}</td></tr>
                <tr><th style="text-align:left;padding:0.5rem;border:1px solid #ddd;background:#f5f5f5;">참석자</th><td style="padding:0.5rem;border:1px solid #ddd;">${participants.join(', ')}</td></tr>
              </table>
              <h2>회의 내용</h2>
            `;

            messages.forEach((msg, index) => {
              if (msg.message_type === 'assistant') {
                htmlContent += `<h3>${index + 1}. AI 분석</h3><p>${markdownToHtml(msg.content)}</p>`;
              } else {
                htmlContent += `<p><strong>질문/요청:</strong> ${msg.content}</p>`;
              }
            });

            content = createHtmlDocument(title, htmlContent);
          }

          const timestamp = Date.now();
          const ext = format === 'markdown' ? 'md' : 'html';
          const outputPath = path.join(fullOutputDir, `meeting_minutes_${timestamp}.${ext}`);
          fs.writeFileSync(outputPath, content, 'utf-8');

          return {
            success: true,
            filePath: path.relative(workspaceRoot, outputPath),
            format,
            title
          };

        } catch (error) {
          logger.error('회의록 내보내기 오류', error);
          throw new Error(`내보내기 실패: ${error.message}`);
        }
      }
    },

    // 프로젝트 자료 내보내기
    {
      name: 'export_project_materials',
      description: '프로젝트의 모든 자료를 하나의 문서로 내보냅니다.',
      inputSchema: {
        type: 'object',
        properties: {
          projectId: {
            type: 'string',
            description: '프로젝트 ID'
          },
          format: {
            type: 'string',
            enum: ['markdown', 'html'],
            default: 'markdown'
          },
          includeContexts: {
            type: 'boolean',
            description: '컨텍스트 포함 여부',
            default: true
          },
          includeResources: {
            type: 'boolean',
            description: '리소스 포함 여부',
            default: true
          }
        },
        required: ['projectId']
      },
      execute: async (args) => {
        const { projectId, format = 'markdown', includeContexts = true, includeResources = true } = args;

        try {
          // 프로젝트 정보
          const project = db.prepare('SELECT * FROM projects WHERE id = ?').get(projectId);
          if (!project) {
            throw new Error('프로젝트를 찾을 수 없습니다');
          }

          let content = '';
          const title = `${project.name} - 프로젝트 자료`;

          if (format === 'markdown') {
            content = `# 📁 ${title}\n\n`;
            content += `> ${project.description || '설명 없음'}\n\n`;
            content += `생성일: ${project.created_at}\n\n`;
            content += `---\n\n`;

            if (includeContexts) {
              const contexts = db.prepare(`
                SELECT * FROM project_context
                WHERE project_id = ?
                ORDER BY importance DESC, created_at DESC
              `).all(projectId);

              if (contexts.length > 0) {
                content += `## 컨텍스트 (${contexts.length}개)\n\n`;
                contexts.forEach((ctx, i) => {
                  content += `### ${i + 1}. ${ctx.title}\n`;
                  content += `- 유형: ${ctx.context_type}\n`;
                  content += `- 중요도: ${ctx.importance}/10\n\n`;
                  content += `${ctx.content}\n\n`;
                  content += `---\n\n`;
                });
              }
            }

            if (includeResources) {
              const resources = db.prepare(`
                SELECT * FROM project_resources
                WHERE project_id = ?
                ORDER BY created_at DESC
              `).all(projectId);

              if (resources.length > 0) {
                content += `## 리소스 (${resources.length}개)\n\n`;
                resources.forEach((res, i) => {
                  content += `### ${i + 1}. ${res.title}\n`;
                  content += `- 유형: ${res.resource_type}\n`;
                  if (res.file_path) {
                    content += `- 파일: ${res.file_path}\n`;
                  }
                  content += `\n${res.content || '(내용 없음)'}\n\n`;
                  content += `---\n\n`;
                });
              }
            }
          } else {
            // HTML 형식
            let htmlContent = `<p><em>${project.description || '설명 없음'}</em></p>`;

            if (includeContexts) {
              const contexts = db.prepare(`
                SELECT * FROM project_context WHERE project_id = ? ORDER BY importance DESC
              `).all(projectId);

              if (contexts.length > 0) {
                htmlContent += `<h2>컨텍스트 (${contexts.length}개)</h2>`;
                contexts.forEach((ctx, i) => {
                  htmlContent += `
                    <div style="margin-bottom:1.5rem;padding:1rem;border:1px solid #ddd;border-radius:8px;">
                      <h3>${i + 1}. ${ctx.title}</h3>
                      <p style="color:#666;font-size:0.9em;">유형: ${ctx.context_type} | 중요도: ${ctx.importance}/10</p>
                      <p>${markdownToHtml(ctx.content)}</p>
                    </div>
                  `;
                });
              }
            }

            content = createHtmlDocument(title, htmlContent);
          }

          const timestamp = Date.now();
          const ext = format === 'markdown' ? 'md' : 'html';
          const outputPath = path.join(fullOutputDir, `project_${projectId}_${timestamp}.${ext}`);
          fs.writeFileSync(outputPath, content, 'utf-8');

          return {
            success: true,
            filePath: path.relative(workspaceRoot, outputPath),
            format,
            projectName: project.name
          };

        } catch (error) {
          logger.error('프로젝트 내보내기 오류', error);
          throw new Error(`내보내기 실패: ${error.message}`);
        }
      }
    },

    // 커스텀 문서 생성
    {
      name: 'create_document',
      description: '마크다운 또는 HTML 문서를 생성합니다.',
      inputSchema: {
        type: 'object',
        properties: {
          title: {
            type: 'string',
            description: '문서 제목'
          },
          content: {
            type: 'string',
            description: '문서 내용 (마크다운)'
          },
          format: {
            type: 'string',
            enum: ['markdown', 'html'],
            default: 'markdown'
          },
          filename: {
            type: 'string',
            description: '파일명 (확장자 제외)'
          },
          author: {
            type: 'string',
            description: '작성자',
            default: 'Athena AI'
          }
        },
        required: ['title', 'content']
      },
      execute: async (args) => {
        const { title, content, format = 'markdown', filename, author = 'Athena AI' } = args;

        try {
          let fileContent = '';
          const timestamp = Date.now();
          const baseName = filename || `document_${timestamp}`;

          if (format === 'markdown') {
            fileContent = `# ${title}\n\n`;
            fileContent += `> 작성자: ${author}\n`;
            fileContent += `> 작성일: ${new Date().toLocaleDateString('ko-KR')}\n\n`;
            fileContent += `---\n\n`;
            fileContent += content;
          } else {
            const htmlContent = markdownToHtml(content);
            fileContent = createHtmlDocument(title, `<p>${htmlContent}</p>`, { author });
          }

          const ext = format === 'markdown' ? 'md' : 'html';
          const outputPath = path.join(fullOutputDir, `${baseName}.${ext}`);
          fs.writeFileSync(outputPath, fileContent, 'utf-8');

          return {
            success: true,
            filePath: path.relative(workspaceRoot, outputPath),
            format,
            title
          };

        } catch (error) {
          logger.error('문서 생성 오류', error);
          throw new Error(`문서 생성 실패: ${error.message}`);
        }
      }
    },

    // 내보내기 목록 조회
    {
      name: 'list_exports',
      description: '내보내기된 파일 목록을 조회합니다.',
      inputSchema: {
        type: 'object',
        properties: {
          format: {
            type: 'string',
            description: '형식별 필터링 (md, html, json, txt)'
          },
          limit: {
            type: 'number',
            default: 20
          }
        }
      },
      execute: async (args) => {
        const { format, limit = 20 } = args;

        try {
          const files = fs.readdirSync(fullOutputDir)
            .filter(f => !format || f.endsWith(`.${format}`))
            .map(f => {
              const filePath = path.join(fullOutputDir, f);
              const stats = fs.statSync(filePath);
              return {
                filename: f,
                path: path.relative(workspaceRoot, filePath),
                size: stats.size,
                createdAt: stats.birthtime.toISOString(),
                format: path.extname(f).slice(1)
              };
            })
            .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))
            .slice(0, limit);

          return {
            success: true,
            files,
            total: files.length,
            exportDir: path.relative(workspaceRoot, fullOutputDir)
          };

        } catch (error) {
          throw new Error(`목록 조회 실패: ${error.message}`);
        }
      }
    }
  ];
}
