'use client';

import { useCallback } from 'react';
import jsPDF from 'jspdf';

interface ExportOptions {
  title: string;
  content: string;
  fileName?: string;
}

export function useExport() {
  // PDF 내보내기
  const exportToPDF = useCallback(async ({ title, content, fileName }: ExportOptions) => {
    try {
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      // 한글 폰트 지원을 위해 기본 설정
      pdf.setFont('helvetica');

      // 제목
      pdf.setFontSize(18);
      pdf.text(title, 20, 20);

      // 날짜
      pdf.setFontSize(10);
      pdf.setTextColor(128, 128, 128);
      pdf.text(`Generated: ${new Date().toLocaleString('ko-KR')}`, 20, 30);

      // 구분선
      pdf.setDrawColor(200, 200, 200);
      pdf.line(20, 35, 190, 35);

      // 본문 - 한글 처리를 위해 줄바꿈 처리
      pdf.setFontSize(11);
      pdf.setTextColor(0, 0, 0);

      const lines = content.split('\n');
      let y = 45;
      const pageHeight = 280;
      const lineHeight = 6;
      const margin = 20;
      const maxWidth = 170;

      for (const line of lines) {
        // 긴 줄은 자동으로 줄바꿈
        const splitLines = pdf.splitTextToSize(line || ' ', maxWidth);

        for (const splitLine of splitLines) {
          if (y > pageHeight) {
            pdf.addPage();
            y = 20;
          }

          // 마크다운 헤딩 스타일링
          if (splitLine.startsWith('# ')) {
            pdf.setFontSize(16);
            pdf.setFont('helvetica', 'bold');
            pdf.text(splitLine.substring(2), margin, y);
            pdf.setFontSize(11);
            pdf.setFont('helvetica', 'normal');
            y += lineHeight + 2;
          } else if (splitLine.startsWith('## ')) {
            pdf.setFontSize(14);
            pdf.setFont('helvetica', 'bold');
            pdf.text(splitLine.substring(3), margin, y);
            pdf.setFontSize(11);
            pdf.setFont('helvetica', 'normal');
            y += lineHeight + 1;
          } else if (splitLine.startsWith('- [ ]') || splitLine.startsWith('- [x]')) {
            // 체크박스 아이템
            const isChecked = splitLine.startsWith('- [x]');
            const itemText = splitLine.substring(6);
            pdf.text(isChecked ? '☑' : '☐', margin, y);
            pdf.text(itemText, margin + 6, y);
            y += lineHeight;
          } else if (splitLine.startsWith('- ')) {
            // 불릿 포인트
            pdf.text('•', margin, y);
            pdf.text(splitLine.substring(2), margin + 4, y);
            y += lineHeight;
          } else {
            pdf.text(splitLine, margin, y);
            y += lineHeight;
          }
        }
      }

      // 푸터
      const pageCount = pdf.internal.pages.length - 1;
      for (let i = 1; i <= pageCount; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.setTextColor(150, 150, 150);
        pdf.text(`Page ${i} of ${pageCount} | Generated by Athena`, 105, 290, { align: 'center' });
      }

      // 다운로드
      const finalFileName = fileName || `${title.replace(/[^a-zA-Z0-9가-힣]/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
      pdf.save(finalFileName);

      return true;
    } catch (error) {
      console.error('PDF export error:', error);
      return false;
    }
  }, []);

  // 공유 링크 생성 (클립보드에 텍스트 복사 + Web Share API)
  const shareContent = useCallback(async ({ title, content }: ExportOptions) => {
    const shareData = {
      title,
      text: content.substring(0, 500) + (content.length > 500 ? '...' : ''),
    };

    // Web Share API 지원 확인
    if (navigator.share && navigator.canShare && navigator.canShare(shareData)) {
      try {
        await navigator.share(shareData);
        return { success: true, method: 'native' };
      } catch (error) {
        if ((error as Error).name !== 'AbortError') {
          console.error('Share error:', error);
        }
        return { success: false, method: 'native' };
      }
    }

    // 폴백: 클립보드에 복사
    try {
      const shareText = `${title}\n\n${content}\n\n---\nShared via Athena`;
      await navigator.clipboard.writeText(shareText);
      return { success: true, method: 'clipboard' };
    } catch (error) {
      console.error('Clipboard error:', error);
      return { success: false, method: 'clipboard' };
    }
  }, []);

  return { exportToPDF, shareContent };
}
